// Package auth defines the authentication domain interface and types.
// The Authenticator interface abstracts the authentication provider so that
// domain and HTTP code never depend on a specific provider SDK.
package auth

import (
	"context"
	"time"

	"github.com/GravelEvolution/united-pass/backend/internal/identity"
)

// AuthenticationStatus represents the outcome of an authentication attempt.
type AuthenticationStatus string

const (
	// StatusAuthenticated means the user has fully authenticated.
	StatusAuthenticated AuthenticationStatus = "authenticated"
	// StatusMFARequired means the user must complete an MFA challenge.
	StatusMFARequired AuthenticationStatus = "mfa_required"
	// StatusInvalidCredentials means the credentials were rejected.
	StatusInvalidCredentials AuthenticationStatus = "invalid_credentials"
	// StatusLocked means the account is locked.
	StatusLocked AuthenticationStatus = "locked"
	// StatusExpired means the credentials or challenge have expired.
	StatusExpired AuthenticationStatus = "expired"
	// StatusProviderUnavailable means the authentication provider could not
	// be reached. This is a server-side failure, not a user error.
	StatusProviderUnavailable AuthenticationStatus = "provider_unavailable"
)

// AuthenticationMethod records how the user authenticated.
type AuthenticationMethod string

const (
	MethodPassword AuthenticationMethod = "password"
	MethodTOTP     AuthenticationMethod = "totp"
	MethodPasskey  AuthenticationMethod = "passkey"
	MethodRecovery AuthenticationMethod = "recovery_code"
)

// MFAMethod is a method available for MFA challenge.
type MFAMethod string

const (
	MFAMethodTOTP     MFAMethod = "totp"
	MFAMethodPasskey  MFAMethod = "passkey"
	MFAMethodRecovery MFAMethod = "recovery_code"
)

// PasswordAuthenticationInput carries credentials for the initial
// authentication step. The password is never logged.
type PasswordAuthenticationInput struct {
	Identifier      string
	Password        string
	ResumeRequestID string
}

// MFAChallengeInput carries the MFA method and verification data. The
// ProviderSessionID references the in-progress authentication session that
// the provider created during the password step; it is always supplied by the
// server from the stored challenge and never comes from the browser.
type MFAChallengeInput struct {
	// ProviderSessionID identifies the provider-side authentication session
	// that must be completed with the second factor.
	ProviderSessionID string
	Method            MFAMethod
	Code              string
	// PasskeyAssertion is used for WebAuthn-based MFA. It is separate from
	// Code to avoid cramming a WebAuthn assertion into a string field.
	PasskeyAssertion string
}

// AuthenticationResult is the outcome of an authentication attempt. When
// Status is Authenticated, UserID and ProviderSessionReference are set.
// When Status is MFARequired, ProviderSessionID, AvailableMethods and
// PasskeyRequestOptions are set.
//
// MFA tokens are generated by the HTTP layer (crypto/rand) and keyed in the
// challenge store; provider credentials never reach the browser.
type AuthenticationResult struct {
	Status   AuthenticationStatus
	UserID   identity.UserID
	Provider string
	// ProviderSessionID identifies the provider-side session that must be
	// completed with a second factor (StatusMFARequired). It is stored
	// server-side in the MFA challenge and never exposed to the browser.
	ProviderSessionID string
	// ProviderSessionReference is the provider-side session handle stored
	// (encrypted at rest) with the created session so logout can revoke it.
	// For ZITADEL this is the session ID only; the session token is never
	// persisted.
	ProviderSessionReference string
	AuthenticationMethods    []AuthenticationMethod
	// PasskeyRequestOptions carries the WebAuthn PublicKeyCredentialRequestOptions
	// (JSON) when StatusMFARequired and passkey is available. The browser uses
	// it for navigator.credentials.get; nil/empty means no passkey challenge.
	PasskeyRequestOptions string
	AvailableMethods      []MFAMethod
}

// Authenticator abstracts the authentication provider. Implementations must
// not leak provider SDK types through this interface.
type Authenticator interface {
	// BeginPasswordAuthentication starts the authentication flow with
	// username/password credentials.
	BeginPasswordAuthentication(
		ctx context.Context,
		input PasswordAuthenticationInput,
	) (AuthenticationResult, error)

	// CompleteMFA completes an MFA challenge using the provided method.
	CompleteMFA(
		ctx context.Context,
		input MFAChallengeInput,
	) (AuthenticationResult, error)

	// RevokeProviderSession revokes the provider-side session. This is a
	// best-effort operation: local session invalidation must not depend on
	// this succeeding.
	RevokeProviderSession(
		ctx context.Context,
		sessionReference string,
	) error
}

// AuthenticationTime returns the current time as the authentication time.
// This is a separate function so tests can control it.
type Clock interface {
	Now() time.Time
}
