// Package auth defines the authentication domain interface and types.
// The Authenticator interface abstracts the authentication provider so that
// domain and HTTP code never depend on a specific provider SDK.
package auth

import (
	"context"
	"encoding/json"
	"log/slog"
	"time"

	"github.com/GravelEvolution/united-pass/backend/internal/identity"
)

// AuthenticationStatus represents the outcome of an authentication attempt.
type AuthenticationStatus string

const (
	// StatusAuthenticated means the user has fully authenticated.
	StatusAuthenticated AuthenticationStatus = "authenticated"
	// StatusMFARequired means the user must complete an MFA challenge.
	StatusMFARequired AuthenticationStatus = "mfa_required"
	// StatusInvalidCredentials means the credentials were rejected.
	StatusInvalidCredentials AuthenticationStatus = "invalid_credentials"
	// StatusLocked means the account is locked.
	StatusLocked AuthenticationStatus = "locked"
	// StatusExpired means the credentials or challenge have expired.
	StatusExpired AuthenticationStatus = "expired"
	// StatusProviderUnavailable means the authentication provider could not
	// be reached. This is a server-side failure, not a user error.
	StatusProviderUnavailable AuthenticationStatus = "provider_unavailable"
)

// AuthenticationMethod records how the user authenticated.
type AuthenticationMethod string

const (
	MethodPassword AuthenticationMethod = "password"
	MethodTOTP     AuthenticationMethod = "totp"
	MethodPasskey  AuthenticationMethod = "passkey"
	MethodRecovery AuthenticationMethod = "recovery_code"
)

// MFAMethod is a method available for MFA challenge.
type MFAMethod string

const (
	MFAMethodTOTP     MFAMethod = "totp"
	MFAMethodPasskey  MFAMethod = "passkey"
	MFAMethodRecovery MFAMethod = "recovery_code"
)

// PasswordAuthenticationInput carries credentials for the initial
// authentication step. The password is never logged.
type PasswordAuthenticationInput struct {
	Identifier      string
	Password        string
	ResumeRequestID string
}

// MFAChallengeInput carries the MFA method and verification data. The
// ProviderSessionID references the in-progress authentication session that
// the provider created during the password step; it is always supplied by the
// server from the stored challenge and never comes from the browser.
type MFAChallengeInput struct {
	// ProviderSessionID identifies the provider-side authentication session
	// that must be completed with the second factor.
	ProviderSessionID string
	Method            MFAMethod
	// Code is the user-entered verification value for totp (and, in future
	// phases, recovery codes). Required only when Method is TOTP.
	Code string
	// PasskeyAssertion is the raw WebAuthn assertion JSON submitted by the
	// browser for Method Passkey. It is forwarded to the provider as-is.
	PasskeyAssertion json.RawMessage
}

// ProviderSessionToken is the in-memory bearer token returned by the
// authenticating provider call (StatusAuthenticated only). The type keeps
// the value unexported and redacts every rendering path (%v/%+v/%#v,
// slog), so the token can travel from the authenticator to the session
// service without ever being printable by accident; the session service
// seals it into the encrypted Version-2 credential immediately and the
// plaintext is dropped.
type ProviderSessionToken struct {
	token string
}

// NewProviderSessionToken wraps a raw provider session token.
func NewProviderSessionToken(token string) ProviderSessionToken {
	return ProviderSessionToken{token: token}
}

// Empty reports whether no token was issued (legacy/MFA paths).
func (t ProviderSessionToken) Empty() bool { return t.token == "" }

// Token returns the raw provider session token (narrow seam for sealing
// into the session credential; never log the returned value).
func (t ProviderSessionToken) Token() string { return t.token }

func (ProviderSessionToken) String() string { return "[redacted provider session token]" }

func (ProviderSessionToken) GoString() string { return "[redacted provider session token]" }

func (ProviderSessionToken) LogValue() slog.Value {
	return slog.StringValue("[redacted provider session token]")
}

// AuthenticationResult is the outcome of an authentication attempt. When
// Status is Authenticated, UserID and ProviderSessionReference are set.
// When Status is MFARequired, ProviderSessionID, AvailableMethods and
// PasskeyRequestOptions are set.
//
// MFA tokens are generated by the HTTP layer (crypto/rand) and keyed in the
// challenge store; provider credentials never reach the browser.
type AuthenticationResult struct {
	Status   AuthenticationStatus
	UserID   identity.UserID
	Provider string
	// ProviderSessionID identifies the provider-side session that must be
	// completed with a second factor (StatusMFARequired). It is stored
	// server-side in the MFA challenge and never exposed to the browser.
	ProviderSessionID string
	// ProviderSessionReference is the provider-side session handle stored
	// (encrypted at rest) with the created session so logout can revoke it.
	// For ZITADEL this is the session ID; together with
	// ProviderSessionToken it is sealed into the versioned
	// ProviderSessionCredential (ADR-0005 §3).
	ProviderSessionReference string
	// ProviderSessionToken is the provider session token returned by the
	// authenticating provider call (StatusAuthenticated only). In-memory
	// bearer material wrapped in the redacted ProviderSessionToken type:
	// the HTTP layer hands it to the session service, which seals it
	// into the encrypted Version-2 credential immediately; it is never
	// logged, rendered or persisted in plaintext.
	ProviderSessionToken  ProviderSessionToken
	AuthenticationMethods []AuthenticationMethod
	// PasskeyRequestOptions carries the WebAuthn PublicKeyCredentialRequestOptions
	// (JSON object) when StatusMFARequired and passkey is available. The
	// browser uses it for navigator.credentials.get; nil means no passkey
	// challenge. The HTTP layer returns it as a JSON object, never as a
	// string, so clients do not need to parse an embedded JSON document.
	PasskeyRequestOptions json.RawMessage
	AvailableMethods      []MFAMethod
}

// Authenticator abstracts the authentication provider. Implementations must
// not leak provider SDK types through this interface.
type Authenticator interface {
	// BeginPasswordAuthentication starts the authentication flow with
	// username/password credentials.
	BeginPasswordAuthentication(
		ctx context.Context,
		input PasswordAuthenticationInput,
	) (AuthenticationResult, error)

	// CompleteMFA completes an MFA challenge using the provided method.
	CompleteMFA(
		ctx context.Context,
		input MFAChallengeInput,
	) (AuthenticationResult, error)

	// RevokeProviderSession revokes the provider-side session. This is a
	// best-effort operation: local session invalidation must not depend on
	// this succeeding.
	RevokeProviderSession(
		ctx context.Context,
		sessionReference string,
	) error
}

// AuthenticationTime returns the current time as the authentication time.
// This is a separate function so tests can control it.
type Clock interface {
	Now() time.Time
}
